version: '3.5'

services:

  msstandart_db:
    container_name: msstandart_db
    image: postgres
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msstandart_db