server:
  port: 8888
  servlet:
    context-path: /msstandart
spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://192.168.0.10:5432/msstandart_db
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true